### ISSUE TITLE
formatDate() in data-api-client depends on system timezone

### ISSUE THREAD

**Issue by filipsuk** [ArsenyYankovsky/typeorm-aurora-data-api-driver#37] opened 2020-05-27 16:18 UTC
I had a problem with inserting values with the `timestamp` mysql data type. Javascript Date object `2020-05-28T03:56:48.466Z` was being transformed to `"2020-05-28 05:56:48"`. (I am in UTC+2 timezone. Server uses UTC, however I encountered this issue during local development.)

Then I tried running the script with 
```bash
$ TZ='UTC' node somescript.js
```

and `2020-05-28T03:56:48.466Z` was correctly transformed to `"2020-05-28 03:56:48"`.

I think the problem might be that aws-sdk does not communicate my system timezone to Aurora Data API and expects UTC.

Related source code: https://github.com/ArsenyYankovsky/data-api-client/blob/support-date/index.js#L189
```js
const formatDate = (date) => {
    const padNumber = (number) => number <= 9 ? '0' + number : number


    const year = date.getFullYear()
    const month = date.getMonth() + 1
    const day = date.getDate()

    const hour = date.getHours()
    const minutes = date.getMinutes()
    const seconds = date.getSeconds()

    return year + '-' + padNumber(month) + '-' + padNumber(day) + ' ' + padNumber(hour) + ':' + padNumber(minutes) + ':' + padNumber(seconds)
  }
```

Expected: timestamp string sent to Data API should be in UTC and not be related to system timezone.

Suggested fix: use UTC variants of Date methods like `Date.prototype.getUTCHours()`

Thanks for this amazing library!

**Comment by ArsenyYankovsky** [comment] 2020-05-30 07:35
@filipsuk Makes sense, will fix. 
I also think it's a temporary fix and in the end it's better to switch to a non-forked version of the `data-api-client` once https://github.com/jeremydaly/data-api-client/pull/44/files is merged.

**Comment by ArsenyYankovsky** [comment] 2020-05-30 11:16
Ok, I tested the proposed fix and generally it should work as expected. My tests used `datetime` type before which I assume was the cause of the issue.
I tried using `timestamp` type instead and indeed has reproduced the issue. However, I cannot make it convert to the js Date object, getting a string back instead. Looking at the TypeORM code it seems like the conversion is not needed when getting it back from a real MySQL database, so it seems like MySQL driver is doing the conversion inside.
@filipsuk could you please share your entity definition or the type that you're using/getting back when using the `timestamp` type? Thank you.

**Comment by filipsuk** [comment] 2020-07-10 13:15
@ArsenyYankovsky Hey, sorry for the delay. I switched to using aurora postgres and recently came to the issue you are talking about. When reading an entity with `timestamptz` column type (or probably any other datetime type), the column is returned as a string.

It seems this has been newly implemented and released here https://github.com/jeremydaly/data-api-client/issues/28

Is there anything preventing the switch to non-forked data-api-client here?

**Comment by ArsenyYankovsky** [comment] 2020-07-10 14:55
I'll definitely check it out and let you know. I don't immediately see any issues with it, but I'll run some tests and if everything go well publish a new version.

**Comment by ArsenyYankovsky** [comment] 2020-07-13 20:48
1.3.3 with non-forked data-api-client has been released

**Closed by ArsenyYankovsky** 2020-07-13 20:48 UTC

**Comment by filipsuk** [comment] 2020-07-14 07:58
Thank you so much @ArsenyYankovsky 👍. I will give it a try.
