### ISSUE TITLE
Postgres enum values

### ISSUE THREAD

**Issue by filipsuk** [ArsenyYankovsky/typeorm-aurora-data-api-driver#44] opened 2020-07-28 12:19 UTC
It seems that enum values when using postgres are not supported. Maybe even the Data API does not support enums in stringValue parameters (I just asked AWS about this).

Similar problem with jsonb type: https://github.com/jeremydaly/data-api-client/issues/34

**Workaround**:

I managed to get enums working by wrapping the value in a function (which tells typeorm to pass it as raw - so it avoids parameters)

example: 
```
status: () => `'${Status.PENDING}'`,

// instead of
status: Status.PENDING,
```

**What also works** is casting (mentioned in the linked issue):

```
UPDATE property SET status=:status::property_status_enum
```
(enum name in schema is `property_status_enum` and passed query parameters: `{status: 'pending'}`)

Casting requires you to use raw queries which kind of goes against typeorm workflow. Could this casting be implemented in this driver or somewhere else? @ArsenyYankovsky

**Comment by ArsenyYankovsky** [comment] 2020-07-28 13:01
I don't think the driver gets any metadata from entities about the type of query parameters and you're able to run raw queries through TypeORM so I don't think there's a generic solution for this. There might be some kind of workaround though that can be used. I'll take a look at it when I have time and let you know if it's possible to fix it.

**Comment by nimrodkor** [comment] 2020-08-02 16:10
Would love this feature too @ArsenyYankovsky

**Comment by filipsuk** [comment] 2020-09-02 16:01
Looks like they are trying to solve the enum problem here https://github.com/jeremydaly/data-api-client/issues/27 but no output yet 😞  I still use have to use raw queries.

**Comment by ffxsam** [comment] 2020-09-03 22:27
Several field types do not work properly, including `uuid`, `jsonb`, `money`, etc.

Reference: https://github.com/typeorm/typeorm/issues/6667

**Comment by ffxsam** [comment] 2020-09-04 00:29
I just learned a cool trick. You can get around these type issues in TypeORM by setting values as functions that return a raw value. E.g.:

```ts
@Entity()
export class Content {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column('money', { nullable: true })
  balance: () => number;

  @Column('uuid', { nullable: true })
  uuid: () => string;
}
```

And then:

```ts
    const content = new Content();

    content.title = 'Title Here';
    content.balance = () => 16.95;
    content.uuid = () => "'e8abf481-f7ff-458f-8078-af76a0a0ca68'";
    await repository.save(content);
```

**Comment by ffxsam** [comment] 2020-09-04 00:30
Even if `data-api-client` could be passed column type information, TypeORM doesn't seem to pass any info about entities/classes to its drivers, so I don't know if this issue will ever be resolved neatly.

**Comment by filipsuk** [comment] 2020-09-24 08:40
also a problem for postgres `date` type (date without time)

**Comment by harm-less** [comment] 2020-09-25 10:43
It's not pretty, but it does the job. I added UUID support in the driver for my own purposes:
https://github.com/harm-less/typeorm-aurora-data-api-driver

Basically what I did is checking every parameter to see if it's a UUID or not. If it is, it will cast it otherwise it does what it does by default:
```typescript
protected transformParameters(parameters?: any[]) {
    if (!parameters) {
      return parameters
    }

    return parameters.map(
      (parameter, index) => {
        const paramName = `param_${index + 1}`;

        // cast to UUID if the parameter is a valid UUID
        if (validate(parameter)) {
          return {
            name: paramName,
            value: parameter,
            cast: 'uuid',
          };
        }
        
        return {[paramName]: parameter};
      })
  }
```

I also needed to make sure I was using `data-api-client` that included this PR from @ffxsam: https://github.com/jeremydaly/data-api-client/pull/57

This is definitely meant as a short-term bandage, so use it at your own risk.

But it could be food for thought and something we could do in fixing certain issues in this discussion as well as TypeORM doesn't provide any metadata to the transformers.

**Comment by harm-less** [comment] 2020-09-25 10:45
@filipsuk Did you see this documentation? Perhaps that could help you:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.calling

But it looks like your date requires casting as well.

**Comment by revmischa** [comment] 2020-10-10 13:30
Having this problem as well, trying to use custom enum types in postgres and it needs the bind value cast to the type, even though it's just a "string"

**Comment by ArsenyYankovsky** [comment] 2020-12-20 17:50
Good news, everyone!

I actually found a way of fixing this and https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/51 and the data type issues in general. I'm really sorry I haven't checked this more in-depth earlier.

If you look at the PostgresDriver  in the TypeORM repository you'll see two methods: [preparePersistentValue](https://github.com/typeorm/typeorm/blob/f27622daf9784d06496975bbbcacdb0938fd2c82/src/driver/postgres/PostgresDriver.ts#L444)  and [prepareHydratedValue](https://github.com/typeorm/typeorm/blob/f27622daf9784d06496975bbbcacdb0938fd2c82/src/driver/postgres/PostgresDriver.ts#L518). Basically, they define how values of different types are converted before being sent a database and after being retrevied from a database. I've successfully added in the enum hack like that:

```
    } else if (
      (
        columnMetadata.type === 'enum'
          || columnMetadata.type === 'simple-enum'
      )
    ) {
      return () => `'${value}'`
    }
```

and it worked. 

We can submit a PR to the TypeORM repository with the modifications required to the both MySQL Aurora and Postgres Aurora drivers. However, it's probably much better to let the driver handle things like that so the fixes are released much faster. This can also be done, but I'm not 100% sure how to approach this. 

The hacky way would be to let TypeORM insert unsupported parameters as a string. Basically, @filipsuk's hack on steroids hidden from developers. 

A better way is to probably provide the type information to the Data API with casts and type hints. I'm not 100% sure how it works though.

**Bonus**: this also solves time/date/datetime/datetime with timezone issue.

**Comment by revmischa** [comment] 2020-12-21 08:59
Would it be useful to add more type hints to https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#batchExecuteStatement-property ?

**Comment by ffxsam** [comment] 2020-12-21 16:20
Not sure if this helps anyone, but we just updated the [Data API Client](https://github.com/jeremydaly/data-api-client) to support casting. [Details here](https://github.com/jeremydaly/data-api-client#type-casting).

**Comment by filipsuk** [comment] 2021-01-15 19:05
@ArsenyYankovsky I tried your solution within preparePersistentValue and prepareHydratedValue and I think it only helps with persisting enum values but does not help when querying them (e.g. using in `find()` `where` condition).. but i am sure some similar edit in typeorm source would solve query issue as well but we just have to find it 🤯

for find conditions we are using typeorm's `Raw()` `FindOperator` as a workaround (i can share more details)

**Comment by wisaac407** [comment] 2021-01-25 22:47
Any updates on this?

**Comment by seawatts** [comment] 2021-01-29 17:36
> Not sure if this helps anyone, but we just updated the [Data API Client](https://github.com/jeremydaly/data-api-client) to support casting. [Details here](https://github.com/jeremydaly/data-api-client#type-casting).

It looks like this might solve the issue. I'm going to look into how we can use this in this library today.

**Comment by ffxsam** [comment] 2021-01-29 17:41
@seawatts Cool, let me know if there's anything else we can do to help get TypeORM working with the RDS Data API!

**Comment by seawatts** [comment] 2021-01-29 18:20
@ffxsam I'm not familiar with the workings of any of these libraries so it will take me a while to understand them. However, at first glance it looks like this might need to be a change upstream in the TypeORM library

**Comment by ffxsam** [comment] 2021-01-29 18:36
In my earlier comment:
https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/44#issuecomment-686831789

I noted that TypeORM wasn't internally passing type info to its drivers, so yeah, changes would have to be made to TypeORM in order for this to work properly.

**Comment by seawatts** [comment] 2021-01-29 19:28
Ah right, I missed that comment. Dang, I don't think I have the cycles for that level of effort currently. We should probably open an issue up on their repo.

**Comment by ArsenyYankovsky** [comment] 2021-03-21 13:11
I've submitted a PR fixing this to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/7483) and released a new 2.0.0 version of the driver. 

While we're waiting for the TypeORM pull request to be merged and a new release, you can use [my fork of TypeORM](https://github.com/ArsenyYankovsky/typeorm), branch `data-api-prepare-hydrate`.

**Comment by davingreen** [comment] 2021-04-01 21:33
> I've submitted a PR fixing this to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/7483) and released a new 2.0.0 version of the driver.
> 
> While we're waiting for the TypeORM pull request to be merged and a new release, you can use [my fork of TypeORM](https://github.com/ArsenyYankovsky/typeorm), branch `data-api-prepare-hydrate`.

Even with your branch of typeorm and running v2.0.3, I'm seeing an error: `column "status" is of type "channel-message-text_status_enum" but expression is of type character varying`

Code if it's helpful:
```typescript
export enum STATUS {
  DRAFT = 'DRAFT',
}

...

  @Column({
    type: 'enum',
    enum: STATUS,
    default: STATUS.DRAFT,
    nullable: false,
  })
  public status?: STATUS

...

  await channelMessageRepository.save(channelMessageRepository.create({}))
```

Is there a workaround? Thanks!

**Comment by davingreen** [comment] 2021-04-01 21:48
I was able to get around it by removing the enum type:
```
  @Column({
    default: STATUS.DRAFT,
    nullable: false,
  })
  public status?: STATUS
```

**Comment by seawatts** [comment] 2021-04-01 23:23
Yeah that works, but then the db doesn't create the column as an enum 😔

**Comment by ArsenyYankovsky** [comment] 2021-04-02 10:31
@seawatts @davingreen I just released a driver with a fix for this (2.0.4). You also don't have to use my fork anymore since new TypeORM 0.3.32 was released. Feel free to comment here or open a new issue if something doesn't work.

**Closed by ArsenyYankovsky** 2021-04-02 10:31 UTC

**Comment by sporkspatula** [comment] 2021-04-19 22:13
@ArsenyYankovsky I am using both 2.0.4 driver and 0.2.32 typeorm and running into the same problem with a default enum. Does your fix work for defaults?

**Comment by tautologistics** [comment] 2021-05-05 02:26
Using typeorm@0.2.32 and typeorm-aurora-data-api-driver@2.1.0 against Aurora Serverless PG via the AWS Data API and not seeing ENUMs being cast when SELECTing records using the respository find methods. Was expecting `AuroraDataApiPostgresDriver.preparePersistentValue` to be called but after tracing, it is not.

Any suggestions? Trying to make a minimal reproducable case...

**Comment by ArsenyYankovsky** [comment] 2021-05-06 15:36
Until we fix the code in TypeORM it will not work because `preparePersistentValue` isn't called for the default.
I guess the only way is to try to work around with following:

```
  @Column({
    default: () => `'${Status.DRAFT}'`,
    nullable: false,
  })
  public status?: STATUS
```

I'm not 100% sure it will work though.
